/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _CaptureRoute } from '../pages/capture';
import { Route as _IndexRoute } from '../pages/';
import { Route as _LoginRoute } from '../pages/login';
import { Route as _ManualInputRoute } from '../pages/manual-input';
import { Route as _ResultRoute } from '../pages/result';
import { Route as _SavedRoute } from '../pages/saved';
import { Route as _ScanRoute } from '../pages/scan';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/capture': (typeof _CaptureRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/login': (typeof _LoginRoute)['_inputType'];
    '/manual-input': (typeof _ManualInputRoute)['_inputType'];
    '/result': (typeof _ResultRoute)['_inputType'];
    '/saved': (typeof _SavedRoute)['_inputType'];
    '/scan': (typeof _ScanRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/capture': (typeof _CaptureRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/login': (typeof _LoginRoute)['_outputType'];
    '/manual-input': (typeof _ManualInputRoute)['_outputType'];
    '/result': (typeof _ResultRoute)['_outputType'];
    '/saved': (typeof _SavedRoute)['_outputType'];
    '/scan': (typeof _ScanRoute)['_outputType'];
  }
}
